---
# tasks file for dev
- name: Install Git
  package: name=git state=latest
  become: yes
- name: Install Vim
  package: name=vim state=latest
  become: yes
- name: Install ansible
  package: name=ansible state=latest
  become: yes

- name: Check for vimrc
  stat:
      path: ~/.vimrc
  register: stat_vimrc

- name: Copy in if not exist
  copy:
      src: .vimrc
      dest: ~/.vimrc
  when: stat_vimrc.stat.exists == False

- name: Create colors dir
  shell: mkdir -p ~/.vim/colors

- name: Get molokai colorscheme
  get_url:
      url: https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
      dest: ~/.vim/colors

- name: Create pathogen dir
  shell: mkdir -p ~/.vim/autoload ~/.vim/bundle 
- name: Pull pathogen
  shell: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
- name: check for pathogen in vimrc
  shell: "cat ~/.vimrc | grep pathogen#infect\\(\\) | wc -l"
  register: pathogen_present

- debug: msg="{{pathogen_present.stdout}}"

- name: Add pathogen to vimrc if not present
  lineinfile:
      path: ~/.vimrc
      insertbefore: BOF
      line: "execute pathogen#infect()"
  when: pathogen_present.stdout == "0"

- name: Vim - Install Lightline
  git:
      repo: git@github.com:itchyny/lightline.vim.git
      dest: ~/.vim/bundle/lightline.vim
      clone: yes
      update: yes
- name: check for pathogen in vimrc
  shell: "cat ~/.vimrc | grep laststatus=2 | wc -l"
  register: laststatus_present

- debug: msg="{{laststatus_present.stdout}}"

- name: Add laststatus to vimrc if not present to fix lightline
  lineinfile:
      path: ~/.vimrc
      line: "set laststatus=2"
  when: laststatus_present.stdout == "0"



- name: Vim - Install Nerdtree
  git:
      repo: https://github.com/scrooloose/nerdtree.git 
      dest: ~/.vim/bundle/nerdtree
      clone: yes
      update: yes

- name: Vim - Install Ale
  git:
      repo: https://github.com/w0rp/ale.git
      dest: ~/.vim/bundle/ale
      clone: yes
      update: yes

- name: Vim - Install Gitgutter
  git:
      repo: git@github.com:airblade/vim-gitgutter.git
      dest: ~/.vim/bundle/vim-gitgutter
      clone: yes
      update: yes
- name: Vim - Install Emmet
  git:
      repo: https://github.com/mattn/emmet-vim.git
      dest: ~/.vim/bundle/emmet
      clone: yes
      update: yes
- name: Vim - Install multiple cursors
  git:
      repo: git@github.com:terryma/vim-multiple-cursors.git
      dest: ~/.vim/bundle/multiple-cursors
      clone: yes
      update: yes
